stages:
  - train 
  - validate
  - register
  - deploy

variables:
  MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
  MLFLOW_TRACKING_USERNAME: $MLFLOW_TRACKING_USERNAME
  MLFLOW_TRACKING_PASSWORD: $MLFLOW_TRACKING_PASSWORD

train-job:
  stage: train
  script:
    - python Model/train.py
  artifacts:
    when: always
    paths:
      - mlruns/

validate-job:
  stage: validate
  script:
    - echo "This job runs validation"

registerclear-job:
  stage: register
  script:
    - echo "This job registers model"

deploy-job:
  stage: deploy
  script:
    - echo "This job deploys model"