stages:
  - train 
  - validate
  - register
  - deploy

variables:
  MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
  MLFLOW_TRACKING_USERNAME: $MLFLOW_TRACKING_USERNAME
  MLFLOW_TRACKING_PASSWORD: $MLFLOW_TRACKING_PASSWORD

build-job:
  stage: train
  script:
    - echo "Training the model"

test-job:
  stage: validate
  script:
    - echo "This job runs validation"

register-job:
  stage: register
  script:
    - echo "This job registers model"

deploy-job:
  stage: deploy
  script:
    - echo "This job deploys model"