apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-deployment
  labels:
    app: spam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spam
  template:
    metadata:
      labels:
        app: spam
    spec:
      containers:
      - name: spam-pod
        image: nginx:latest
        ports:
        - containerPort: 80
        # resources:
        #   requests:
        #     cpu: "100m"  
        #     memory: "128Mi" 
        #   limits:
        #     cpu: "200m"  
        #     memory: "256Mi"