apiVersion: v1
kind: Service
metadata:
  name: spam-service
  labels:   
    app: spam
spec:
  selector:
    app: spam
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
  type: LoadBalancer