apiVersion: v1
kind: Service
metadata:
  name: wine-prediction-service
  labels:   
    app: wine-prediction
spec:
  selector:
    app: wine-prediction    
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000